config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'users/profile'

  post 'users/upload'

  post 'users/create_slideshow'

  post 'users/delete_image'

  post 'users/delete_slideshow'

  get 'users/profile', as: 'user_root'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  require 'net/ftp'

  def profile
  	@Galleries = Gallery.all
    @gallery_names = []
    @Galleries.each { |gallery| @gallery_names.push gallery.name  }
  end

  def upload 
    newImage = Image.create(:name => params[:image_name], :url =>'', :user_id => current_user.id, :slideshow_id => params[:gallery_name])    
    file = params[:file]
    @url = 'http://ant478.esy.es/' + newImage.id.to_s + '_' + file.original_filename
    ftp = Net::FTP.new('ftp.ant478.esy.es')
    ftp.login(user = 'u347184519', passwd = 'enigma')
    ftp.storbinary("STOR " + newImage.id.to_s + '_' + file.original_filename, StringIO.new(file.read), Net::FTP::DEFAULT_BLOCKSIZE)
    ftp.quit()
    newImage.update_attributes(:url => @url)
  end

  def delete_image
  end

  def create_slideshow
    Gallery.create(:name => params[:gallery_name], :description => params[:gallery_description], :user_id => current_user.id)
  end

  def delete_slideshow
    @Galleries = Gallery.all
    @Galleries.each { |gallery|
      if gallery.name == params[:gallery_name]
        gallery.destroy
        break
      end
    }
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slideshow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/create_slideshow.html.erb
<b>Created</b>
<%= link_to 'Home', user_root_path %>

app/views/users/delete_image.html.erb
<b>DeletedI</b>
<%= link_to 'Home', user_root_path %>

app/views/users/delete_slideshow.html.erb
<b>DeletedSlideShow</b>
<%= link_to 'Home', user_root_path %>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>
<b> Картинки2 </b>

<%= form_tag({action: :create_slideshow}, multipart: true) do %> <!--Create category form-->
  <%= label_tag(:gallery_name, 'Gallery name:') %>
  <%= text_field_tag(:gallery_name) %>
  <%= label_tag(:gallery_description, 'Gallery Description:') %>
  <%= text_field_tag(:gallery_description) %>
  <%= submit_tag("Create slideshow") %>
<% end %>

<br>

<%= form_tag({action: :delete_slideshow}, multipart: true) do %>
  <%= select_tag(:gallery_name, options_for_select(@gallery_names)) %>
  <%= submit_tag("Delete slideshow") %>
<% end %>

<br>

<%= form_tag({action: :upload}, multipart: true) do %> <!--Upload image form-->
  <%= label_tag(:image_name, 'Image Name:') %>
  <%= text_field_tag(:image_name) %>
  <%= label_tag(:gallery_name, 'Gallery Name:') %>
  <%= select_tag(:gallery_name, options_for_select(@gallery_names)) %>
  <%= file_field_tag :file %>
  <%= submit_tag("Upload image") %>
<% end %>

app/views/users/upload.html.erb
<b>Uploaded</b>
<%= link_to 'Home', user_root_path %>
<br>
<%= link_to 'Link', @url %>